// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUZpMdwgpJ6LA8qlrHhLap9cGcrVCtwBI',
    appId: '1:934361748118:web:266644c12282bf310568b7',
    messagingSenderId: '934361748118',
    projectId: 'last-exam-188de',
    authDomain: 'last-exam-188de.firebaseapp.com',
    storageBucket: 'last-exam-188de.firebasestorage.app',
    measurementId: 'G-W9E5WSG2PV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCGtDHypSj86diySNnfA--nIFIHKEoK0E',
    appId: '1:934361748118:android:67e677ca798d95c30568b7',
    messagingSenderId: '934361748118',
    projectId: 'last-exam-188de',
    storageBucket: 'last-exam-188de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIR4UJaC2-QTWchrzgYoloENAt322CvcI',
    appId: '1:934361748118:ios:147dca5f71af5e790568b7',
    messagingSenderId: '934361748118',
    projectId: 'last-exam-188de',
    storageBucket: 'last-exam-188de.firebasestorage.app',
    androidClientId: '934361748118-q9kr2j12h5f0rfatseoie7pqptiqaavs.apps.googleusercontent.com',
    iosClientId: '934361748118-i9d6rmaj387vhlfe0qb821c9s21rpc5u.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLastExam',
  );

}