// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLyVvs9hyFlJ0R2qlC6XtwC25Gbx1v8kM',
    appId: '1:6007384474:web:5f641679cd6bf083b4f223',
    messagingSenderId: '6007384474',
    projectId: 'auth-9e085',
    authDomain: 'auth-9e085.firebaseapp.com',
    storageBucket: 'auth-9e085.firebasestorage.app',
    measurementId: 'G-E44XRNMRV0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzUOHSEoZFEGDP_l-S91dootOiGewgwNI',
    appId: '1:6007384474:android:c58cafcdf9a1eb62b4f223',
    messagingSenderId: '6007384474',
    projectId: 'auth-9e085',
    storageBucket: 'auth-9e085.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkKn38ced1imrjez6PDDHkkSMMgRUU4HQ',
    appId: '1:6007384474:ios:0da59436e32cfcb4b4f223',
    messagingSenderId: '6007384474',
    projectId: 'auth-9e085',
    storageBucket: 'auth-9e085.firebasestorage.app',
    iosClientId: '6007384474-n0od82ojkrjnbad8j691aias7mm1u4ho.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLastExam',
  );

}